---
title: "Wei Yang Tham's CV"
author: Magdalena Bennett
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['styles_mb.css','resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(glue)
library(tidyverse)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')

# Load csv with position info
position_data <- read_csv('positionsv2.csv')
position_data <- position_data %>% filter(in_resume==TRUE) #Only keep true values
```


```{r}
# When in export mode the little dots are unaligned, so fix that. 
if(PDF_EXPORT){
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-paper-plane"></i> wtham@hbs.edu
- <i class="fa fa-twitter"></i> wytham88
- <i class="fa fa-github"></i> github.com/maibennett
- <i class="fa fa-link"></i> [magdalenabennett.com](http://magdalenabennett.com/)
- <i class="fa fa-phone"></i> (512) 471-3322
- <i class="fa fa-building-o"></i> Of. CBA 6.476 

  
Main
================================================================================

Wei Yang Tham {#title}
--------------------------------------------------------------------------------


```{r}
#intro_text <- "**Research Interests**: Causal Inference Methodologies; Impact Evaluations; #Economics of Education, particularly in segregation and school choice."

#cat(sanitize_links(intro_text))
#<span style="font-size:larger;"> **Research Interests**: Causal Inference Methodologies; Impact Evaluations; Economics #of Education, particularly in segregation and school choice. <span>

#<div style="margin-bottom:16px">
```

<div class="grid-container">
<!-- top row -->
```{r summary, child = 'research_int.Rmd'}
```

```{r contact-info, child = 'contact_info.Rmd'}
```
</div>
--------------------------------------------------------------------------------

Academic Positions {data-icon=briefcase data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'academic_positions')
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```

Awards, Honors, and Grants {data-icon=star}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'awards')
```

Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'publications')
```


Working Papers and On-going Research {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'workingpapers')
```

Presentations {data-icon=bar-chart}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'presentations')
```


Research Experience {data-icon=search}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'research_experience')
```



Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'teaching_experience')
#<br> (space)
```


</div>

<br>

<div class="nogrid-container">
<div class-"col-6 grid-item">
</div>
<!-- top row -->
```{block type="col-6 grid-item", echo=TRUE}
<span style="font-size:larger;">**Software Skills**<span>

<div class="info-box">

| Left | Left |
|:------|:-----|
| <i class="fa fa-calculator"></i>| Software: R, Stata, Git, SQL, MATLAB |
<!-- | <i class="fa fa-laptop"></i>| Programming Languages: Python (advanced) | -->
<!-- | <i class="fa fa-desktop"></i>| Other software: ArcGIS (advanced), MS Excel (advanced), CSPro (advanced) | -->
</div>
```
</div>

<div class="nogrid-container">
<div class-"col-6 grid-item">
</div>
```{block type="col-6 grid-item", echo=TRUE}
<span style="font-size:larger;">**Additional information**<span> 

<div class="info-box">

| Left | Left |
|:------|:-----|
| <i class="fa fa-comment"></i>| Languages: English (native), Chinese (fluent), French (basic) |
| <i class="fa fa-map-marker-alt"></i>| Nationality: Singapore |
</div>
```
</div>

<!-- pagedown::chrome_print('C:/Users/mc72574/Dropbox/CV/pagedown/cv-master/mbennett_cv3.html') -->